dataset_conf:
    filter_conf:
        max_length: 2048
        min_length: 0
    resample_conf:
        resample_rate: 16000
    speed_perturb: false
    feature_extraction_conf:
        feature_type: 'mfcc'
        num_ceps: 80
        num_mel_bins: 80
        frame_shift: 10
        frame_length: 25
        dither: 1.0
    feature_dither: 0.0
    spec_aug: false
    spec_aug_conf:
        num_t_mask: 2
        num_f_mask: 2
        max_t: 20
        max_f: 40
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    batch_conf:
        batch_size: 64

# checkpoint_kws: null
# checkpoint_se: null
checkpoint_kws: /home/user/Workspace/wekws/examples/speechcommand_v1/s0/exp/mdtc_origin/avg_10.pt
checkpoint_se: /home/user/Workspace/wekws/examples/speechcommand_v1/se0/exp/convtasnet/10best_avg.pt

se_model:
    num_sources: 1
    num_blocks: 4  # default 8 -> 4 
    num_repeats: 2 # default 3 -> 2
    loss_mode: SI-SDR
    loss_weight: 0.01

kws_model:
    hidden_dim: 64
    preprocessing:
        type: linear
    backbone:
        type: mdtc
        num_stack: 4
        stack_size: 4
        kernel_size: 5
        hidden_dim: 64
        causal: True
    classifier:
        type: global
        dropout: 0.5
    criterion: ce

optim: adam
optim_conf:
    lr: 0.001
    weight_decay: 1e-5

training_config:
    grad_clip: 5
    max_epoch: 1
    log_interval: 10
    criterion: ce
