dataset_conf:
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    batch_conf:
        batch_size: 64

model:
    num_sources: 1
    num_blocks: 4  # default 8 -> 4 
    num_repeats: 2 # default 3 -> 2
    loss_mode: SI-SDR


optim: adam
optim_conf:
    lr: 0.003
    weight_decay: 0.0001

training_config:
    grad_clip: 5
    max_epoch: 100
    log_interval: 10

