dataset_conf:
    filter_conf:
        max_length: 2048
        min_length: 0
    resample_conf:
        resample_rate: 16000
    speed_perturb: false
    feature_extraction_conf:
        feature_type: 'mfcc'
        num_ceps: 80
        num_mel_bins: 80
        frame_shift: 10
        frame_length: 25
        dither: 1.0
    # feature_extraction_conf:
    #     feature_type: 'logmel'
    #     n_mels: 40
    #     n_fft: 512
    #     hop_length: 160
    #     win_length: 480
    feature_dither: 0.0
    spec_aug: true
    spec_aug_conf:
        num_t_mask: 2
        num_f_mask: 2
        max_t: 20
        max_f: 40
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    batch_conf:
        batch_size: 32

model:
    tau: 2.0 # model size BC-ResNet-tau [1, 1.5, 2, 3, 6, 8]
    hidden_dim: 32
    preprocessing:
        type: none
    backbone:
        type: bc_resnet
    classifier:
        type: identity

optim: sgd  
optim_conf:
    init_lr: 0.1
    lr_lower_limit: 0
    lr: 0.0
    weight_decay: 0.001
    momentum: 0.9  # SGD 전용
    warmup_epochs: 5

training_config:
    grad_clip: 5
    max_epoch: 100
    log_interval: 10
    criterion: ce
